# Generated by Django 2.0.7 on 2018-07-27 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20180725_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='employers',
            field=models.ManyToManyField(related_name='courses', to='courses.Employer'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
