# Generated by Django 2.0.7 on 2018-07-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tutors'),
        ('courses', '0007_auto_20180730_1635'),
    ]

    operations = [
    ]
