# Generated by Django 2.0.7 on 2018-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_merge_20180730_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='brief',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
